<?php

/**
 * @file fg_extra.module
 */

define('FIELDGROUPEXTRAJSPATH', drupal_get_path('module', 'fg_extra') . '/fg_extra.js');

/**
 * Implements hook_css_alter().
 *
 */
function fg_extra_js_alter(&$js) {
  if (module_exists('field_group')) {
    $path = drupal_get_path('module', 'field_group') . '/field_group.js';
    if (isset($js[$path])) {
      $weight = $js[$path]['weight'];
      $js[FIELDGROUPEXTRAJSPATH]['weight'] = $weight + 1;
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 *
 */
function fg_extra_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('field_group')) {
    $form['#attached']['js'][FIELDGROUPEXTRAJSPATH] = array(
      'data' => FIELDGROUPEXTRAJSPATH,
    );
  }
//  if ($form_id == 'person_node_form') {
//    $form['#submit'][] = 'fg_extra_submit_handler';
//
//  }
}


function fg_extra_fieldset($variables) {
  $t=1;
}


//function fg_extra_submit_handler($form, &$form_state) {
//  $errors = form_get_errors();
//  $cur = current_path();
//  $t=1;
//  $form_state['redirect'] = 'node/10';
////  drupal_goto($cur,array('fragment' => 'comment-form'));
////  $form_state['redirect'] = array(
////    $cur,
////    array('fragment' => 'comment-form'),
////  );
//  $t=1;
//}